attraction/urls.py
from django.urls import path

from . import views

app_name = 'attraction'

urlpatterns = [
    path('hotels/', views.hotel_list, name="hotel_list"),
    path('hotel/<int:pk>/', views.hotel_detail, name="hotel_detail"),
    path('hotel/<int:pk>/delete', views.hotel_delete, name="hotel_delete"),
    path('hotel/<int:pk>/add_room/', views.add_room, name="add_room"),
    path('hotel/<int:pk>/remove_room/<int:room_pk>/', views.remove_room, name="remove_room"),
    path('hotel/<int:pk>/add_restaurant/', views.add_restaurant, name="add_restaurant"),
    path('hotel/<int:pk>/remove_restaurant/', views.remove_restaurant, name="remove_restaurant"),
]

city/urls.py
from django.urls import path

from . import views

app_name = 'city'

urlpatterns = [
    path('', views.city_list, name='city_list'),
    path('<int:pk>/', views.city_detail, name="city_detail"),
    path('<int:pk>/delete/', views.city_delete, name="city_delete"),
    path('<int:pk>/update/', views.city_update, name="city_update"),
]

epona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core.views import index, get_hotels, vw_login, vw_register, vw_logout, get_restaurants
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('attractions/', include('attraction.urls')),
    path('cities/', include('city.urls')),
    path('packages/', include('package.urls')),
    path('create/', include('create.urls')),
    path('client/', include('client.urls')),
    path('login/', vw_login, name='vw_login'),
    path('register/', vw_register, name='vw_register'),
    path('logout/', vw_logout, name='vw_logout'),
    path('ajax/hoteis/', get_hotels, name='get_hotels'),
    path('ajax/restaurants/', get_restaurants, name='get_restaurants'),
]

urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

package/urls.py
from django.urls import path

from . import views

app_name = 'package'

urlpatterns = [
    path('', views.filter_packages, name="filter_packages"),
    path('all_packages', views.list_packages, name='list_packages'),
    path('<int:pk>/', views.package_detail, name="package_detail"),
    path('<int:pk>/delete', views.package_delete, name="package_delete"),
    path('<int:pk>/update', views.package_update, name="package_update"),
    path('<int:pk>/buy', views.buy_package, name="buy_package"),
    path('<int:pk>/sell', views.sell_package, name="sell_package"),
    path('<int:package_pk>/add_attraction', views.add_attraction, name="add_attraction"),
    path('<int:pk>/remove_attraction/<int:pack_attr_pk>', views.remove_attraction, name="remove_attraction"),
]

package/models.py
from django.db import models

from city.models import City
from attraction.models import Attraction, Hotel
from client.models import Client

class Package(models.Model):
    price = models.FloatField()
    start_date = models.DateField()
    end_date = models.DateField()
    city = models.ForeignKey(City, related_name='cities_package', on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, related_name='hotels_package', on_delete=models.CASCADE)
    attractions = models.ManyToManyField(Attraction, through='PackageAttraction')
    clients = models.ManyToManyField(Client, related_name="client_packages", blank=True)

class PackageAttraction(models.Model):
    package = models.ForeignKey(Package, related_name='packages', on_delete=models.CASCADE)
    attraction = models.ForeignKey(Attraction, related_name='attractions', on_delete=models.CASCADE)
    visitation_date = models.DateField()

package/views.py
from django.shortcuts import render, get_object_or_404, redirect
from city.models import City
from attraction.models import Hotel, Museum, Park, ConcertHall, Church, Attraction
from .models import Package, PackageAttraction
from client.models import Client
from .filters import PackageFilter
from django.http import HttpResponseRedirect
from django.urls import reverse
import json

def list_packages(request):
    context = {}
    package_data = []

    filtered_packages = PackageFilter(
        request.GET,
        queryset=Package.objects.all()
    )

    context['filtered_packages'] =  filtered_packages

    for package in filtered_packages.qs:
        attractions = package.attractions.all()
        tourist_spots = [attraction.touristspot for attraction in attractions]

        has_museum = any(tourist_spot for tourist_spot in tourist_spots if tourist_spot.type_tourist_spot == 0)
        has_park = any(tourist_spot for tourist_spot in tourist_spots if tourist_spot.type_tourist_spot == 2)
        has_concert_hall = any(tourist_spot for tourist_spot in tourist_spots if tourist_spot.type_tourist_spot == 3)
        has_church = any(tourist_spot for tourist_spot in tourist_spots if tourist_spot.type_tourist_spot == 1)

        package_info = {
            'package': package,
            'has_museum': has_museum,
            'has_park': has_park,
            'has_church': has_church,
            'has_concert_hall': has_concert_hall
        }

        package_data.append(package_info)
        

    return render(request, 'package/list.html', {
        'package_data': package_data,
        'filtered_packages': filtered_packages})


def package_detail(request, pk):
    package = get_object_or_404(Package, pk=pk)
    package_attractions = PackageAttraction.objects.filter(package=package)
    client = None
    has_bought = False
    
    if request.user.is_authenticated:
        client = request.user.client
        has_bought = client.client_packages.filter(pk=pk).exists()


    return render(request, 'package/detail.html', {
        'package': package,
        'package_attractions': package_attractions,
        'client': client,
        'has_bought': has_bought,
    })

def package_delete(request, pk):
    package = get_object_or_404(Package, pk=pk)

    if request.method == 'POST':
        package.delete()

        return redirect('index')
    
    return render(request, 'package/delete.html', {'package': package})

def package_update(request, pk):
    package = get_object_or_404(Package, pk=pk)
    cities = City.objects.all()

    if request.method == 'POST':
        package.price = request.POST.get('price')
        package.start_date = request.POST.get('start-date')
        package.end_date = request.POST.get('start-date')
        city_id = request.POST.get('city')
        package.city = City.objects.get(pk=city_id)
        hotel_id = request.POST.get('hotel')
        package.hotel = Hotel.objects.get(pk=hotel_id)
        package.save()

        return HttpResponseRedirect(reverse('package:package_detail', args=[package.id]))

    return render(request, 'package/update.html', {
        'package': package,
        'cities': cities
    })

def add_attraction(request, package_pk):
    package = get_object_or_404(Package, pk=package_pk)

    if request.method == 'POST':
        attraction_id = request.POST.get('atracao')
        visitation_date = request.POST.get('visitation-date')

        attraction = get_object_or_404(Attraction, pk=attraction_id)

        new_package_attraction = PackageAttraction(package=package, attraction=attraction,
                                                   visitation_date=visitation_date)
        new_package_attraction.save()

        return redirect('package:package_detail', package_pk)


    city = package.city
    museums = Museum.objects.filter(city=city)
    parks = Park.objects.filter(city=city)
    concert_halls = ConcertHall.objects.filter(city=city)
    churches = Church.objects.filter(city=city)

    return render(request, 'package_attraction/add_attraction.html', {
        'museums_json': json.dumps(list(museums.values('id', 'name'))),
        'churches_json': json.dumps(list(churches.values('id', 'name'))),
        'parks_json': json.dumps(list(parks.values('id', 'name'))),
        'concert_halls_json': json.dumps(list(concert_halls.values('id', 'name'))),
        'package': package,
    })

def remove_attraction(request, pk, pack_attr_pk):
    package_attraction = get_object_or_404(PackageAttraction, pk=pack_attr_pk)

    if request.method == 'POST':
        package_attraction.delete()

        return redirect('package:package_detail', pk)

def buy_package(request, pk):
    if request.method == 'POST':
        package = get_object_or_404(Package, pk=pk)
        client = get_object_or_404(Client, user_id=request.user.id)

        package.clients.add(client)

        return redirect('client:client_packages', request.user.id)
    else: 
        return redirect('package:package_detail', pk)

def sell_package(request, pk):
    if request.method == 'POST':
        package = get_object_or_404(Package, pk=pk)
        user = request.user
        client = get_object_or_404(Client, user=user)

        package.clients.remove(client)
        
        return redirect('client:client_packages', request.user.id)
    else: 
        return redirect('package:package_detail', pk)


def filter_packages(request):
    if request.method== 'POST':
        city_id = request.POST['city']
        start_date = request.POST['start-date']
        end_date = request.POST['end-date']

        city = City.objects.get(pk=city_id)        
        packages = Package.objects.filter(city=city, start_date=start_date,
                                          end_date=end_date)
        
        return render(request, 'packages.html', {'packages': packages})

# def hotel_detail(request, pk):
#     hotel = get_object_or_404(Hotel, pk=pk)
#     rooms = Room.objects.filter(hotel__id=pk)

#     return render(request, 'hotel/detail.html', {
#         'hotel': hotel,
#         'rooms': rooms,
#     })

        
    #     hotel = Hotel.objects.get(pk=pk)
    #     new_room = Room(hotel=hotel, type=type, price=price, quantity=quantity)
    #     new_room.save()

    #     return redirect('attraction:hotel_detail', pk)
    
    # return render(request, 'hotel/add_room.html', {'hotel_pk':pk})

package/templates/package/delete.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title">Deletar pacote</h5>
            <p class="card-text">Quer mesmo deletar o pacote para a cidade {{ package.city.name }}?</p>
            <form method="POST" action="">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Confirmar </button>
              <a href="{% url 'package:package_detail' package.id %}" class="btn btn-secondary">Cancelar</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

package/templates/package/detail.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container mt-4">
    <h1>Detalhes do Pacote de Viagem</h1>
    <hr>

    <!-- Informações do Pacote de Viagem -->
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">R${{ package.price }}</h5>
        <h6 class="card-text">{{ package.city }}</h6>
        <p class="card-text">Data de Início: {{ package.start_date|date:"d/m/Y" }} </p>
        <p class="card-text">Data Fim: {{ package.end_date|date:"d/m/Y" }}</p>
        <p class="card-text">Hotel: <a href="{% url 'attraction:hotel_detail' package.hotel.id %}">{{ package.hotel }} </a></p>

        {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <a href="{% url 'package:package_update' package.id %}" >   
                        <button class="btn btn-primary">Atualizar</button>
                    </a>
                    <a href="{% url 'package:package_delete' package.id %}">
                        <button type="button" class="btn btn-danger">Deletar</button>
                    </a>
                {% endif %}

                {% if has_bought %}
                    <form method="POST" action="{% url 'package:sell_package' package.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger mt-3">Desfazer compra</button>
                    </form>
                {% else %}        
                    <form method="POST" action="{% url 'package:buy_package' package.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success mt-3">Comprar</button>
                    </form>
                {% endif %}   
            {% endif %}
      </div>
    </div>

    <!-- Lista de Atrações -->
    <div class="card mt-4">
      <div class="card-body">
        <h5 class="card-title">Atrações</h5>
        <ul class="list-group">
          
        {% for package_attraction in package_attractions %}
            {% if package_attraction.attraction.type_attraction == 2 %}
                {% if package_attraction.attraction.touristspot.type_tourist_spot == 0 %}
                <li class="list-group-item">
                    <h3 class="mb-1">{{ package_attraction.attraction.touristspot.name }} (Museu)</h3>
                    <h5 class="mb-1">{{ package_attraction.visitation_date|date:"d/m/Y" }}</h5>
                    <h6 class="mb-1">{{ package_attraction.attraction.touristspot.address }}</h6>
                    <p class="mb-1"> {{ package_attraction.attraction.touristspot.description }}</p>
                    <p class="mb-1">Fundado em: {{ package_attraction.attraction.touristspot.museum.foundation_date|date:"d/m/Y" }} </p>
                    <p class="mb-1">Quantidade de salas: {{ package_attraction.attraction.touristspot.museum.number_rooms }} </p>
                    {% if user.is_superuser %}
                    <form method="POST" action="{% url 'package:remove_attraction' pk=package.id pack_attr_pk=package_attraction.id %}">
                        {% csrf_token %}
                        <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
                    </form>
                    {% endif %}
                </li>
                {% endif %}

                {% if package_attraction.attraction.touristspot.type_tourist_spot == 1 %}
                <li class="list-group-item">
                    <h3 class="mb-1">{{ package_attraction.attraction.touristspot.name }} (Igreja)

                    </h3>
                    <h5 class="mb-1">{{ package_attraction.visitation_date|date:"d/m/Y" }}</h5>
                    <h6 class="mb-1">{{ package_attraction.attraction.touristspot.address }}</h6>
                    <p class="mb-1">{{ package_attraction.attraction.touristspot.description }}</p>
                    <p class="mb-1">Estilo de construção: {{ package_attraction.attraction.touristspot.church.construction_style }}</p>
                    <p class="mb-1">Data de construção: {{ package_attraction.attraction.touristspot.church.construction_date|date:"d/m/Y" }}</p>
                    {% if user.is_superuser %}
                    <form method="POST" action="{% url 'package:remove_attraction' pk=package.id pack_attr_pk=package_attraction.id %}">
                        {% csrf_token %}
                        <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
                    </form>
                    {% endif %}
                </li>
                {% endif %}

                {% if package_attraction.attraction.touristspot.type_tourist_spot == 2 %}
                <li class="list-group-item">
                    <h3 class="mb-1">{{ package_attraction.attraction.touristspot.name }} (Parque)

                    </h3>
                    <h5 class="mb-1">{{ package_attraction.visitation_date|date:"d/m/Y" }}</h5>
                    <h6 class="mb-1">{{ package_attraction.attraction.touristspot.address }}</h6>
                    <p class="mb-1">{{ package_attraction.attraction.touristspot.description }}</p>
                    <p class="mb-1">Tipo: {{ package_attraction.attraction.touristspot.park.type }} </p>
                    {% if user.is_superuser %}
                    <form method="POST" action="{% url 'package:remove_attraction' pk=package.id pack_attr_pk=package_attraction.id %}">
                        {% csrf_token %}
                        <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
                    </form>
                    {% endif %}
                </li>
                {% endif %}

                {% if package_attraction.attraction.touristspot.type_tourist_spot == 3 %}
                <li class="list-group-item">
                    <h3 class="mb-1">{{ package_attraction.attraction.touristspot.name }} (Casa de show)

                    </h3>
                    <h5 class="mb-1">{{ package_attraction.visitation_date|date:"d/m/Y" }}</h5>
                    <h6 class="mb-1">{{ package_attraction.attraction.touristspot.address }}</h6>
                    <p class="mb-1">{{ package_attraction.attraction.touristspot.description }}</p>
                    <p class="mb-1">Aberto a partir das {{ package_attraction.attraction.touristspot.concerthall.start_time|time:"H:i" }}</p>
                    <p class="mb-1">Fechado no(a) {{ package_attraction.attraction.touristspot.concerthall.closing_day }}</p>
                    
                    {% if package_attraction.attraction.touristspot.concerthall.restaurant_hall %}
                    <p class="mb-1">{{ package_attraction.attraction.touristspot.concerthall.restaurant_hall.name}} - {{ package_attraction.attraction.touristspot.concerthall.restaurant_hall.category}}</p>
                    {% endif %}
                    
                    {% if user.is_superuser %}
                    <form method="POST" action="{% url 'package:remove_attraction' pk=package.id pack_attr_pk=package_attraction.id %}">
                        {% csrf_token %}
                        <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
                    </form>
                    {% endif %}
                </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        </ul>
        
        {% if  user.is_superuser %}
        <a href="{% url 'package:add_attraction' package.id %}" class="btn btn-primary mt-3">Adicionar Atração</a>
        {% endif %}
      </div>
    </div>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
{% endblock %}

package/templates/package/list.html
{% extends 'core/base.html' %}

{% block content %}
 
    <form class="" method="get">
        <div class="filter-wrap">
            <div class="filter-container">
                <p>Preço: </p>
                <p>{{ filtered_packages.form.price }} </p>
                <p>Cidade: </p>
                <p>{{ filtered_packages.form.city }}</p>
                <p>Data de ida: </p>
                <p>{{ filtered_packages.form.start_date }}</p>
                <p>Data de volta: </p>
                <p>{{ filtered_packages.form.end_date }}</p><br>
                <button type="submit">Filtrar</button>
            </div>
        </div>
    </form>

    

        <section id="most-searched">
            <div class="searched-text">
                <h1>Pacotes</h1>
            </div>
        


    <div class="card-container">
        {% for package_info in package_data %}
        <div class="packet-card">
        <figure class="card-image">
            <img src="/media/{{ package_info.package.city.image }}">
        </figure>
        <div class="card-content">
            <a href="{% url 'package:package_detail' package_info.package.id %}">Pacote</a>
            <h3><h1>{{ package_info.package.city.name }} - {{ package_info.package.city.state.abbreviation }}</h1></h3>
            <p class="tour-date">{{ package_info.package.start_date|date:"d/m/Y" }} - {{ package_info.package.end_date|date:"d/m/Y" }}</p>
            <div class="hotel-info">
            <figure class="hotel-icon">
                <img src="/media/icons/hoteis.png" alt="">
            </figure>
            <h5>{{ package_info.package.hotel.name }}</h5>
            </div>
            <div class="attractions-icon">
            {% if package_info.has_museum %}
                <img src='/media/icons/galeria.png'>
            {% endif %}
            {% if package_info.has_church %}
                <img src='/media/icons/igreja.png'>
            {% endif %}
            {% if package_info.has_park %}
                <img src="/media/icons/parque.png" alt="">
            {% endif %}
            {% if package_info.has_concert_hall %}
                <img src="/media/icons/show.png" alt="">
            {% endif %}
            </div>
            <h4>R${{ package_info.package.price }}</h4>
        </div>
        </div>
        {% empty %}
        <h2>Não há pacotes disponíveis para essa data</h2>
    {% endfor %}
    </div>

</section>
<!-- 
<script>
    const button = document.querySelector("button")
    const modal = document.querySelector("dialog")

    button.onclick= function () {
        modal.showModal()
    }
</script> -->

{% endblock %}

package/templates/package/update.html
{% extends 'core/base.html' %}

{% block content %}

<div class="form-container">
    <div class="form">
            <form action="" method="POST">
                {% csrf_token %}
                <h2 class="form-heading">Atualizar pacote</h2>
                <input type="text" id="price" name="price" placeholder="Preço" value="{{ package.price }}" required>
                <input type="date" id="start-date" name="start-date" value="{{ package.start_date }}" required>
                <input type="date" id="end-date" value="{{ package.end_date }}" name="end-date" required>

                <select id="city" name="city" required>
                    {% for city in cities %}
                        <option value="{{ city.id }}" {% if city.id == package.city.id %} selected {% endif %}>{{ city.name }} - {{ city.state.abbreviation }}</option>
                    {% endfor %}
                </select>

                <select id="hotel" name="hotel" required>
                </select>

                <button type="submit">Atualizar</button>
            </form>
        </div>
    </div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
      var citySelect = document.getElementById('city');
      var hotelSelect = document.getElementById('hotel');
  
      citySelect.addEventListener('change', function() {
        var cityId = citySelect.value;
        var url = '/ajax/hoteis/?city_id=' + cityId;
  
        fetch(url)
          .then(function(response) {
            return response.json();
          })
          .then(function(data) {
            hotelSelect.innerHTML = '';
  
            data.hotels.forEach(function(hotel) {
              var option = document.createElement('option');
              option.value = hotel.id;
              option.textContent = hotel.name;
              hotelSelect.appendChild(option);
            });
          });
      });
    });
  </script>

{% endblock %}
  
  
  
  