attraction/urls.py
from django.urls import path

from . import views

app_name = 'attraction'

urlpatterns = [
    path('hotels/', views.hotel_list, name="hotel_list"),
    path('hotel/<int:pk>/', views.hotel_detail, name="hotel_detail"),
    path('hotel/<int:pk>/delete', views.hotel_delete, name="hotel_delete"),
    path('hotel/<int:pk>/add_room/', views.add_room, name="add_room"),
    path('hotel/<int:pk>/remove_room/<int:room_pk>/', views.remove_room, name="remove_room"),
    path('hotel/<int:pk>/add_restaurant/', views.add_restaurant, name="add_restaurant"),
    path('hotel/<int:pk>/remove_restaurant/', views.remove_restaurant, name="remove_restaurant"),
]

city/urls.py
from django.urls import path

from . import views

app_name = 'city'

urlpatterns = [
    path('', views.city_list, name='city_list'),
    path('<int:pk>/', views.city_detail, name="city_detail"),
    path('<int:pk>/delete/', views.city_delete, name="city_delete"),
    path('<int:pk>/update/', views.city_update, name="city_update"),
]

epona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core.views import index, get_hotels, vw_login, vw_register, vw_logout, get_restaurants
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('attractions/', include('attraction.urls')),
    path('cities/', include('city.urls')),
    path('packages/', include('package.urls')),
    path('create/', include('create.urls')),
    path('client/', include('client.urls')),
    path('login/', vw_login, name='vw_login'),
    path('register/', vw_register, name='vw_register'),
    path('logout/', vw_logout, name='vw_logout'),
    path('ajax/hoteis/', get_hotels, name='get_hotels'),
    path('ajax/restaurants/', get_restaurants, name='get_restaurants'),
]

urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

attraction/models.py
from django.db import models
from city.models import City 

class Attraction(models.Model):
    city = models.ForeignKey(City, related_name='cities', on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    type_attraction = models.IntegerField()


class CategoryRestaurant(models.Model):
    description = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.description
    
class Restaurant(Attraction):
    name = models.CharField(max_length=30)
    category = models.ForeignKey(CategoryRestaurant, related_name='categories_restaurant', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

class CategoryHotel(models.Model):
    description = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.description

class Hotel(Attraction):
    name = models.CharField(max_length=20)
    category = models.ForeignKey(CategoryHotel, related_name='categories_hotel', on_delete=models.CASCADE)
    number_rooms = models.IntegerField()
    restaurant_hotel = models.OneToOneField(Restaurant, related_name='restaurants_hotel', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return self.name

class Room(models.Model):
    hotel = models.ForeignKey(Hotel, related_name='hotels', on_delete=models.CASCADE)
    type = models.CharField(max_length=20)
    price = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self) -> str:
        return self.type

class TouristSpot(Attraction):
    description = models.CharField(max_length=300)
    type_tourist_spot = models.IntegerField()
    name = models.CharField(max_length=100)

class ConcertHall(TouristSpot):
    start_time = models.TimeField()
    closing_day = models.CharField(max_length=15)
    restaurant_hall = models.OneToOneField(Restaurant, related_name='restaurants_hall', null=True, blank=True, on_delete=models.SET_NULL)

class Church(TouristSpot):
    construction_date = models.DateField()
    construction_style = models.CharField(max_length=50)

class Park(TouristSpot):
    type = models.CharField(max_length=15)

class Museum(TouristSpot):
    number_rooms = models.IntegerField()
    foundation_date = models.DateField()

class Founder(models.Model):
    name = models.CharField(max_length=30)
    birth_date = models.DateField()
    death_date = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=15)
    professional_activity = models.CharField(max_length=15)
    museums = models.ManyToManyField(Museum)

attraction/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Hotel, Room, Restaurant

def hotel_list(request):
    hotels = Hotel.objects.order_by('city')

    return render(request, 'hotel/list.html', {
        'hotels': hotels
    })


def hotel_detail(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)
    rooms = Room.objects.filter(hotel__id=pk)

    return render(request, 'hotel/detail.html', {
        'hotel': hotel,
        'rooms': rooms,
    })

def hotel_delete(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)

    if request.method == 'POST':
        hotel.delete()

        return redirect('index')
    
    return render(request, 'hotel/delete.html', {'hotel': hotel})


def add_room(request, pk):
    if request.method == 'POST':
        type = request.POST['type']
        price = request.POST['price']
        quantity = request.POST['quantity']
        
        hotel = Hotel.objects.get(pk=pk)
        new_room = Room(hotel=hotel, type=type, price=price, quantity=quantity)
        new_room.save()

        return redirect('attraction:hotel_detail', pk)
    
    return render(request, 'hotel/add_room.html', {'hotel_pk':pk})

def remove_room(request, pk, room_pk):
    room = get_object_or_404(Room, pk=room_pk)
    hotel = get_object_or_404(Hotel, pk=pk)

    if request.method == 'POST':
        room.delete()

        return redirect('attraction:hotel_detail', pk)


def add_restaurant(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)

    if request.method == 'POST':
        restaurant_id = request.POST['restaurant']

        restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

        hotel.restaurant_hotel = restaurant
        hotel.save()

        return redirect('attraction:hotel_detail', pk)

    restaurants = Restaurant.objects.filter(city=hotel.city)

    return render(request, 'hotel/add_restaurant.html', {
        'restaurants': restaurants
    })

def remove_restaurant(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)

    if request.method == 'POST':
        hotel.restaurant_hotel = None
        hotel.save()

        return redirect('attraction:hotel_detail', pk)

attraction/templates/hotel/add_restaurant.html
{% extends 'core/base.html' %}

{% block content %}
<div class="form-container">
<div class="form">
        <form action="" method="POST">
            {% csrf_token %}
            <select name="restaurant" required>
                {% for restaurant in restaurants %}
                    <option value="{{ restaurant.id }}">{{ restaurant.name }}</option>
                {% endfor %}
            </select>
            <button type="submit">Enviar</button>
        </form>
    </div>
</div>
{% endblock %}

attraction/templates/hotel/add_room.html
{% extends 'core/base.html' %}

{% block content %}
<div class="form-container">
<div class="form">
        <form action="" method="POST">
            {% csrf_token %}
            <h2 class="form-heading">Cadastro de quarto</h2>
            <input type="text" id="type" name="type" placeholder="Tipo de quarto" required>
            <input type="text" id="price" name="price" placeholder="Preço" required>
            <input type="text" id="quantity" name="quantity" placeholder="Quantidade" required>
            <button type="submit">Enviar</button>
        </form>
    </div>
</div>
{% endblock %}

attraction/templates/hotel/delete.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title">Deletar hotel</h5>
            <p class="card-text">Quer mesmo deletar o hotel {{ hotel.nome }}?</p>
            <form method="POST" action="">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Confirmar</button>
              <a href="{% url 'attraction:hotel_detail' hotel.id %}" class="btn btn-secondary">Cancelar</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

attraction/templates/hotel/detail.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
<div class="container mt-4">
  <h1>Detalhes do Hotel</h1>
  <hr>

  <!-- Informações do Hotel -->
  <div class="card">
    <!-- <img src="caminho/para/imagem.jpg" class="card-img-top" alt="Imagem do Hotel"> -->
    <div class="card-body">
      <h5 class="card-title">{{ hotel.name }}</h5>
      <p class="card-text">Endereço: {{ hotel.address }}, {{ hotel.city.name}} - {{ hotel.city.state.abbreviation }}</p>
      <p class="card-text">Categoria: {{ hotel.category.description }} estrelas</p>
      <p class="card-text">Número de Quartos: {{ hotel.number_rooms }}</p>
      <!-- <a href="{% url 'attraction:hotel_delete' hotel.id %}" class="btn btn-primary">Atualizar</a>
      <a href="{% url 'attraction:hotel_delete' hotel.id %}" class="btn btn-danger">Deletar</a> -->
    </div>
  </div>

  <!-- Informações do Restaurante -->
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Restaurante</h5>
      {% if hotel.restaurant_hotel == None %}
        <a class="btn btn-success" href="{% url 'attraction:add_restaurant' pk=hotel.id %}">Adicionar restaurante</a>
      {% else %}
        <p class="card-text">{{ hotel.restaurant_hotel.name }} - {{ hotel.restaurant_hotel.category.description }} 
        {% if user.is_superuser %}
        <form method="POST" action="{% url 'attraction:remove_restaurant' pk=hotel.id %}">
          {% csrf_token %}
          <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
        </form>
        {% endif %}
          </p>
      {% endif %}
    </div>
  </div>

  <!-- Tipos de Quartos -->
  <div class="card mt-4">
    <div class="card-body">
      <h5 class="card-title">Tipos de Quartos</h5>
      <table class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Quantidade</th>
          </tr>
        </thead>
        <tbody>
          {% for room in rooms %}
          <tr>
            <td>{{ room.type }}</td>
            <td>{{ room.price }}</td>
            <td>{{ room.quantity }}</td>
            {% if user.is_superuser %}
            <td>
              <form method="POST" action="{% url 'attraction:remove_room' pk=hotel.id room_pk=room.id %}">
                {% csrf_token %}
                <button class="btn btn-sm btn-danger" type="submit">Deletar</button>
              </form>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
          <!-- Adicione mais linhas conforme necessário -->
        </tbody>
      </table>
      {% if user.is_superuser %}
      <a class="btn btn-success" href="{% url 'attraction:add_room' pk=hotel.id %}">Adicionar Tipo de Quarto</a>
      {% endif %}
    </div>
  </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}
   

attraction/templates/hotel/list.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container">
    <div class="container">
        <h1>Lista de Hotéis</h1>
        <table class="table">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Endereço</th>
                <th>Estrelas</th>
            </tr>
            </thead>
            <tbody>
            {% for hotel in hotels %}
            <tr>
                <td><a href="{% url 'attraction:hotel_detail' hotel.id %}">{{ hotel.name }}</td>
                <td>{{ hotel.address }}, {{ hotel.city.name }} - {{ hotel.city.state.abbreviation }}</td>
                <td>{{ hotel.category.description}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}