city/urls.py
from django.urls import path

from . import views

app_name = 'city'

urlpatterns = [
    path('', views.city_list, name='city_list'),
    path('<int:pk>/', views.city_detail, name="city_detail"),
    path('<int:pk>/delete/', views.city_delete, name="city_delete"),
    path('<int:pk>/update/', views.city_update, name="city_update"),
]

create/urls.py
from django.contrib.admin.views.decorators import user_passes_test
from django.urls import path

from . import views

app_name = 'create'

def is_superuser(user):
    return user.is_superuser

urlpatterns = [
    path('city/', views.create_city, name="create_city"),
    path('hotel/', views.create_hotel, name="create_hotel"),
    path('restaurant/', views.create_restaurant, name="create_restaurant"),
    path('museum/', views.create_museum, name="create_museum"),
    path('church/', views.create_church, name="create_church"),
    path('park/', views.create_park, name="create_park"),
    path('concerthall/', views.create_concert_hall, name="create_concert_hall"),
    path('package/', views.create_package, name="create_package"),
    path('founder/', views.create_founder, name="create_founder"),
    path('', user_passes_test(is_superuser) (views.create), name="create")
]

epona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core.views import index, get_hotels, vw_login, vw_register, vw_logout, get_restaurants
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('attractions/', include('attraction.urls')),
    path('cities/', include('city.urls')),
    path('packages/', include('package.urls')),
    path('create/', include('create.urls')),
    path('client/', include('client.urls')),
    path('login/', vw_login, name='vw_login'),
    path('register/', vw_register, name='vw_register'),
    path('logout/', vw_logout, name='vw_logout'),
    path('ajax/hoteis/', get_hotels, name='get_hotels'),
    path('ajax/restaurants/', get_restaurants, name='get_restaurants'),
]

urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

city/models.py
from django.db import models


class State(models.Model):
    name = models.CharField(max_length=30)
    abbreviation = models.CharField(max_length=2)

    class Meta:
        ordering = ('name',)

    def __str__(self) -> str:
        return self.name

class City(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    state = models.ForeignKey(State, related_name='cities', on_delete=models.CASCADE)
    population = models.IntegerField()

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Cities'

    def __str__(self) -> str:
        return self.name

city/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import City, State
from django.http import HttpResponseRedirect
from django.urls import reverse


def city_list(request):
    cities = City.objects.order_by('state')

    return render(request, 'city/list.html', {
        'cities': cities,
    })

def city_detail(request, pk):
    city = get_object_or_404(City, pk=pk)

    return render(request, 'city/detail.html', {
        'city': city
    })

def city_delete(request, pk):
    city = get_object_or_404(City, pk=pk)

    if request.method == 'POST':
        city.delete()

        return redirect('index')
    
    return render(request, 'city/delete.html', {'city': city})

def city_update(request, pk):
    city = get_object_or_404(City, pk=pk)
    states = State.objects.all()

    if request.method == 'POST':
        city.name = request.POST.get('name')
        state_id = request.POST.get('state')
        city.state = State.objects.get(pk=state_id)
        city.population = request.POST.get('population')
        city.save()

        return HttpResponseRedirect(reverse('city:city_detail', args=[city.id]))


    return render(request, 'city/update.html', {
        'city': city,
        'states': states,
    })

city/templates/city/delete.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mt-5">
          <div class="card-body">
            <h5 class="card-title">Deletar cidade</h5>
            <p class="card-text">Quer mesmo deletar a cidade {{ city.name }}?</p>
            <form method="POST" action="">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Confirmar </button>
              <a href="{% url 'city:city_detail' city.id %}" class="btn btn-secondary">Cancelar</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

city/templates/city/detail.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mt-5">
          <img src="{{ city.image.url }}" class="card-img-top" alt="City Image">
          <div class="card-body">
            <h5 class="card-title">{{ city.name }}</h5>
            <p class="card-text">{{ city.state.name }}</p>
            <p class="card-text">População: {{ city.population }}</p>
            <a href="{% url 'city:city_update' city.id %}">
                <button type="button" class="btn btn-primary mt-3">Editar</button>
            </a>
            <a href="{% url 'city:city_delete' city.id %}">
                <button type="button" class="btn btn-danger mt-3">Deletar</button>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

city/templates/city/list.html
{% extends 'core/base.html' %}

{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<style>
    .city-card {
      max-width: 400px;
      margin-bottom: 20px;
    }
    .city-card img {
      width: 100%;
      height: auto;
    }
</style>

<div class="container">
    <h1>Lista de Cidades <a href="{% url 'create:create_city' %}" class="btn btn-primary">Adicionar cidade</a></h1>
    <div class="row">
      
      {% for city in cities %}
      <div class="col-md-6">
        <div class="city-card">
          <img src="/media/{{ city.image }}">
          <div class="card-body">
            <h5 class="card-title">{{ city.name }}</h5>
            <p class="card-text">{{ city.state.name}} - {{city.state.abbreviation}} </p>
            <p class="card-text">População: {{ city.population }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>




{% endblock %}

city/templates/city/update.html
{% extends 'core/base.html' %}


{% block content %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Update City</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name:</label>
                    <input type="text" id="id_name" name="name" value="{{ city.name }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_state">State:</label>
                    <select id="id_state" name="state" class="form-control">
                        {% for state in states %}
                            <option value="{{ state.id }}" {% if state.id == city.state.id %} selected {% endif %}>
                                {{ state.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_population">Population:</label>
                    <input type="number" id="id_population" name="population" value="{{ city.population }}" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary mt-3">Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}